// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddExtensionAndContinue(arg1) {
  return window['go']['app']['App']['AddExtensionAndContinue'](arg1);
}

export function AddSearchHistory(arg1) {
  return window['go']['app']['App']['AddSearchHistory'](arg1);
}

export function AddTypeAndContinue(arg1) {
  return window['go']['app']['App']['AddTypeAndContinue'](arg1);
}

export function AddWorkToCollection(arg1, arg2) {
  return window['go']['app']['App']['AddWorkToCollection'](arg1, arg2);
}

export function AnalyzeCollection(arg1) {
  return window['go']['app']['App']['AnalyzeCollection'](arg1);
}

export function AnalyzeCollectionHeadings(arg1) {
  return window['go']['app']['App']['AnalyzeCollectionHeadings'](arg1);
}

export function AnalyzeWork(arg1) {
  return window['go']['app']['App']['AnalyzeWork'](arg1);
}

export function AuditCollectionStyles(arg1) {
  return window['go']['app']['App']['AuditCollectionStyles'](arg1);
}

export function AuditWorkStyles(arg1, arg2) {
  return window['go']['app']['App']['AuditWorkStyles'](arg1, arg2);
}

export function AutoImportFiles(arg1) {
  return window['go']['app']['App']['AutoImportFiles'](arg1);
}

export function AutoImportFilesWithEdits(arg1, arg2) {
  return window['go']['app']['App']['AutoImportFilesWithEdits'](arg1, arg2);
}

export function BackupWork(arg1) {
  return window['go']['app']['App']['BackupWork'](arg1);
}

export function BatchBackupWorks(arg1) {
  return window['go']['app']['App']['BatchBackupWorks'](arg1);
}

export function BatchMoveMarkedFiles(arg1) {
  return window['go']['app']['App']['BatchMoveMarkedFiles'](arg1);
}

export function BatchRevealInFinder(arg1) {
  return window['go']['app']['App']['BatchRevealInFinder'](arg1);
}

export function BatchSyncWorkTemplate(arg1) {
  return window['go']['app']['App']['BatchSyncWorkTemplate'](arg1);
}

export function BatchUpdateWorkField(arg1, arg2, arg3) {
  return window['go']['app']['App']['BatchUpdateWorkField'](arg1, arg2, arg3);
}

export function BrowseForFolder(arg1) {
  return window['go']['app']['App']['BrowseForFolder'](arg1);
}

export function CancelBuild() {
  return window['go']['app']['App']['CancelBuild']();
}

export function CancelImport() {
  return window['go']['app']['App']['CancelImport']();
}

export function CheckImportConflict(arg1) {
  return window['go']['app']['App']['CheckImportConflict'](arg1);
}

export function CheckLibreOffice() {
  return window['go']['app']['App']['CheckLibreOffice']();
}

export function CheckWorkPath(arg1) {
  return window['go']['app']['App']['CheckWorkPath'](arg1);
}

export function CleanDocxStyles(arg1, arg2) {
  return window['go']['app']['App']['CleanDocxStyles'](arg1, arg2);
}

export function ClearAnalysisTabs() {
  return window['go']['app']['App']['ClearAnalysisTabs']();
}

export function ClearPartCache(arg1, arg2) {
  return window['go']['app']['App']['ClearPartCache'](arg1, arg2);
}

export function CloseStatusBar() {
  return window['go']['app']['App']['CloseStatusBar']();
}

export function CompleteSetup() {
  return window['go']['app']['App']['CompleteSetup']();
}

export function CopyBookPDFText(arg1) {
  return window['go']['app']['App']['CopyBookPDFText'](arg1);
}

export function CopyCoverToClipboard(arg1) {
  return window['go']['app']['App']['CopyCoverToClipboard'](arg1);
}

export function CopyTemplateToLibrary(arg1, arg2) {
  return window['go']['app']['App']['CopyTemplateToLibrary'](arg1, arg2);
}

export function CreateBackup(arg1) {
  return window['go']['app']['App']['CreateBackup'](arg1);
}

export function CreateBook(arg1) {
  return window['go']['app']['App']['CreateBook'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['app']['App']['CreateCollection'](arg1);
}

export function CreateNewWork(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CreateNewWork'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNote(arg1) {
  return window['go']['app']['App']['CreateNote'](arg1);
}

export function CreateOrganization(arg1) {
  return window['go']['app']['App']['CreateOrganization'](arg1);
}

export function CreateSubmission(arg1) {
  return window['go']['app']['App']['CreateSubmission'](arg1);
}

export function CreateWork(arg1) {
  return window['go']['app']['App']['CreateWork'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['app']['App']['DeleteBackup'](arg1);
}

export function DeleteBook(arg1) {
  return window['go']['app']['App']['DeleteBook'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['app']['App']['DeleteCollection'](arg1);
}

export function DeleteCollectionPermanent(arg1) {
  return window['go']['app']['App']['DeleteCollectionPermanent'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['app']['App']['DeleteNote'](arg1);
}

export function DeleteNotePermanent(arg1) {
  return window['go']['app']['App']['DeleteNotePermanent'](arg1);
}

export function DeleteOrganization(arg1) {
  return window['go']['app']['App']['DeleteOrganization'](arg1);
}

export function DeleteOrganizationPermanent(arg1) {
  return window['go']['app']['App']['DeleteOrganizationPermanent'](arg1);
}

export function DeleteSubmission(arg1) {
  return window['go']['app']['App']['DeleteSubmission'](arg1);
}

export function DeleteSubmissionPermanent(arg1) {
  return window['go']['app']['App']['DeleteSubmissionPermanent'](arg1);
}

export function DeleteWork(arg1) {
  return window['go']['app']['App']['DeleteWork'](arg1);
}

export function DeleteWorkPermanent(arg1, arg2) {
  return window['go']['app']['App']['DeleteWorkPermanent'](arg1, arg2);
}

export function DetectLibreOffice() {
  return window['go']['app']['App']['DetectLibreOffice']();
}

export function DismissAnnotation(arg1, arg2) {
  return window['go']['app']['App']['DismissAnnotation'](arg1, arg2);
}

export function DuplicateWork(arg1) {
  return window['go']['app']['App']['DuplicateWork'](arg1);
}

export function EmitStatus(arg1, arg2) {
  return window['go']['app']['App']['EmitStatus'](arg1, arg2);
}

export function EnsureTemplatesDir() {
  return window['go']['app']['App']['EnsureTemplatesDir']();
}

export function ExportAllCSV() {
  return window['go']['app']['App']['ExportAllCSV']();
}

export function ExportAllTables() {
  return window['go']['app']['App']['ExportAllTables']();
}

export function ExportBookPDFWithParts(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ExportBookPDFWithParts'](arg1, arg2, arg3, arg4);
}

export function ExportCollectionFolder(arg1) {
  return window['go']['app']['App']['ExportCollectionFolder'](arg1);
}

export function ExportCoverPDF(arg1, arg2) {
  return window['go']['app']['App']['ExportCoverPDF'](arg1, arg2);
}

export function ExportToSubmissions(arg1) {
  return window['go']['app']['App']['ExportToSubmissions'](arg1);
}

export function FTSBatchContent(arg1) {
  return window['go']['app']['App']['FTSBatchContent'](arg1);
}

export function FTSBuildIndex() {
  return window['go']['app']['App']['FTSBuildIndex']();
}

export function FTSCheckStaleness() {
  return window['go']['app']['App']['FTSCheckStaleness']();
}

export function FTSDeleteIndex() {
  return window['go']['app']['App']['FTSDeleteIndex']();
}

export function FTSGetContent(arg1) {
  return window['go']['app']['App']['FTSGetContent'](arg1);
}

export function FTSGetStatus() {
  return window['go']['app']['App']['FTSGetStatus']();
}

export function FTSSearch(arg1) {
  return window['go']['app']['App']['FTSSearch'](arg1);
}

export function FTSUpdateIndex() {
  return window['go']['app']['App']['FTSUpdateIndex']();
}

export function GeneratePath(arg1) {
  return window['go']['app']['App']['GeneratePath'](arg1);
}

export function GetAllSubmissionViews() {
  return window['go']['app']['App']['GetAllSubmissionViews']();
}

export function GetAnalysisEnabled() {
  return window['go']['app']['App']['GetAnalysisEnabled']();
}

export function GetAppState() {
  return window['go']['app']['App']['GetAppState']();
}

export function GetAvailableProviders() {
  return window['go']['app']['App']['GetAvailableProviders']();
}

export function GetBatchPDFPageSizes(arg1) {
  return window['go']['app']['App']['GetBatchPDFPageSizes'](arg1);
}

export function GetBook(arg1) {
  return window['go']['app']['App']['GetBook'](arg1);
}

export function GetBookByCollection(arg1) {
  return window['go']['app']['App']['GetBookByCollection'](arg1);
}

export function GetBookParts(arg1) {
  return window['go']['app']['App']['GetBookParts'](arg1);
}

export function GetCollection(arg1) {
  return window['go']['app']['App']['GetCollection'](arg1);
}

export function GetCollectionAnalysis(arg1) {
  return window['go']['app']['App']['GetCollectionAnalysis'](arg1);
}

export function GetCollectionAnalysisHistory(arg1) {
  return window['go']['app']['App']['GetCollectionAnalysisHistory'](arg1);
}

export function GetCollectionDeleteConfirmation(arg1) {
  return window['go']['app']['App']['GetCollectionDeleteConfirmation'](arg1);
}

export function GetCollectionHasMarkedWorks(arg1) {
  return window['go']['app']['App']['GetCollectionHasMarkedWorks'](arg1);
}

export function GetCollectionHasSuppressedWorks(arg1) {
  return window['go']['app']['App']['GetCollectionHasSuppressedWorks'](arg1);
}

export function GetCollectionIsBook(arg1) {
  return window['go']['app']['App']['GetCollectionIsBook'](arg1);
}

export function GetCollectionWorks(arg1) {
  return window['go']['app']['App']['GetCollectionWorks'](arg1);
}

export function GetCollections() {
  return window['go']['app']['App']['GetCollections']();
}

export function GetCoverImageData(arg1) {
  return window['go']['app']['App']['GetCoverImageData'](arg1);
}

export function GetCoverPDFPath(arg1) {
  return window['go']['app']['App']['GetCoverPDFPath'](arg1);
}

export function GetCoversDir() {
  return window['go']['app']['App']['GetCoversDir']();
}

export function GetDashboardStats(arg1) {
  return window['go']['app']['App']['GetDashboardStats'](arg1);
}

export function GetDefaultTemplatePath() {
  return window['go']['app']['App']['GetDefaultTemplatePath']();
}

export function GetDistinctValues(arg1, arg2) {
  return window['go']['app']['App']['GetDistinctValues'](arg1, arg2);
}

export function GetDuotropeURL(arg1) {
  return window['go']['app']['App']['GetDuotropeURL'](arg1);
}

export function GetEnumLists() {
  return window['go']['app']['App']['GetEnumLists']();
}

export function GetExportFolderPath() {
  return window['go']['app']['App']['GetExportFolderPath']();
}

export function GetExportTables() {
  return window['go']['app']['App']['GetExportTables']();
}

export function GetFileConfig() {
  return window['go']['app']['App']['GetFileConfig']();
}

export function GetFileModTimes(arg1) {
  return window['go']['app']['App']['GetFileModTimes'](arg1);
}

export function GetFileServerPort() {
  return window['go']['app']['App']['GetFileServerPort']();
}

export function GetGalleyInfo(arg1) {
  return window['go']['app']['App']['GetGalleyInfo'](arg1);
}

export function GetMarkedWorksInCollection(arg1) {
  return window['go']['app']['App']['GetMarkedWorksInCollection'](arg1);
}

export function GetNotes(arg1, arg2) {
  return window['go']['app']['App']['GetNotes'](arg1, arg2);
}

export function GetOrganization(arg1) {
  return window['go']['app']['App']['GetOrganization'](arg1);
}

export function GetOrganizationDeleteConfirmation(arg1) {
  return window['go']['app']['App']['GetOrganizationDeleteConfirmation'](arg1);
}

export function GetOrganizations() {
  return window['go']['app']['App']['GetOrganizations']();
}

export function GetOrganizationsWithNotes() {
  return window['go']['app']['App']['GetOrganizationsWithNotes']();
}

export function GetOrgsFilterOptions() {
  return window['go']['app']['App']['GetOrgsFilterOptions']();
}

export function GetPDFPageSize(arg1) {
  return window['go']['app']['App']['GetPDFPageSize'](arg1);
}

export function GetPartCacheStatus(arg1) {
  return window['go']['app']['App']['GetPartCacheStatus'](arg1);
}

export function GetPreviewURL(arg1) {
  return window['go']['app']['App']['GetPreviewURL'](arg1);
}

export function GetPublicationReadiness(arg1) {
  return window['go']['app']['App']['GetPublicationReadiness'](arg1);
}

export function GetReportNames() {
  return window['go']['app']['App']['GetReportNames']();
}

export function GetSearchHistory() {
  return window['go']['app']['App']['GetSearchHistory']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSubmission(arg1) {
  return window['go']['app']['App']['GetSubmission'](arg1);
}

export function GetSubmissionDeleteConfirmation(arg1) {
  return window['go']['app']['App']['GetSubmissionDeleteConfirmation'](arg1);
}

export function GetSubmissionViewsByCollection(arg1) {
  return window['go']['app']['App']['GetSubmissionViewsByCollection'](arg1);
}

export function GetSubmissionViewsByOrg(arg1) {
  return window['go']['app']['App']['GetSubmissionViewsByOrg'](arg1);
}

export function GetSubmissionViewsByWork(arg1) {
  return window['go']['app']['App']['GetSubmissionViewsByWork'](arg1);
}

export function GetSubmissions() {
  return window['go']['app']['App']['GetSubmissions']();
}

export function GetSubmissionsByWork(arg1) {
  return window['go']['app']['App']['GetSubmissionsByWork'](arg1);
}

export function GetSubmissionsFilterOptions() {
  return window['go']['app']['App']['GetSubmissionsFilterOptions']();
}

export function GetSupportingInfo(arg1) {
  return window['go']['app']['App']['GetSupportingInfo'](arg1);
}

export function GetTab(arg1) {
  return window['go']['app']['App']['GetTab'](arg1);
}

export function GetTableState(arg1) {
  return window['go']['app']['App']['GetTableState'](arg1);
}

export function GetTemplatesDir() {
  return window['go']['app']['App']['GetTemplatesDir']();
}

export function GetTitlePageStyles(arg1) {
  return window['go']['app']['App']['GetTitlePageStyles'](arg1);
}

export function GetValidExtensions() {
  return window['go']['app']['App']['GetValidExtensions']();
}

export function GetWork(arg1) {
  return window['go']['app']['App']['GetWork'](arg1);
}

export function GetWorkAnalysis(arg1) {
  return window['go']['app']['App']['GetWorkAnalysis'](arg1);
}

export function GetWorkAnalysisHistory(arg1) {
  return window['go']['app']['App']['GetWorkAnalysisHistory'](arg1);
}

export function GetWorkBookAuditStatus(arg1) {
  return window['go']['app']['App']['GetWorkBookAuditStatus'](arg1);
}

export function GetWorkCollections(arg1) {
  return window['go']['app']['App']['GetWorkCollections'](arg1);
}

export function GetWorkDeleteConfirmation(arg1) {
  return window['go']['app']['App']['GetWorkDeleteConfirmation'](arg1);
}

export function GetWorkFullPath(arg1) {
  return window['go']['app']['App']['GetWorkFullPath'](arg1);
}

export function GetWorkMarked(arg1) {
  return window['go']['app']['App']['GetWorkMarked'](arg1);
}

export function GetWorkSkipAudits(arg1) {
  return window['go']['app']['App']['GetWorkSkipAudits'](arg1);
}

export function GetWorkTemplatePath(arg1) {
  return window['go']['app']['App']['GetWorkTemplatePath'](arg1);
}

export function GetWorks() {
  return window['go']['app']['App']['GetWorks']();
}

export function GetWorksFilterOptions() {
  return window['go']['app']['App']['GetWorksFilterOptions']();
}

export function ImportWork(arg1, arg2) {
  return window['go']['app']['App']['ImportWork'](arg1, arg2);
}

export function IsFirstRun() {
  return window['go']['app']['App']['IsFirstRun']();
}

export function IsValidExtension(arg1) {
  return window['go']['app']['App']['IsValidExtension'](arg1);
}

export function ListBackups() {
  return window['go']['app']['App']['ListBackups']();
}

export function ListTemplates() {
  return window['go']['app']['App']['ListTemplates']();
}

export function MoveWorkFile(arg1) {
  return window['go']['app']['App']['MoveWorkFile'](arg1);
}

export function OpenBookPDF(arg1) {
  return window['go']['app']['App']['OpenBookPDF'](arg1);
}

export function OpenCoverPDF(arg1) {
  return window['go']['app']['App']['OpenCoverPDF'](arg1);
}

export function OpenDocument(arg1) {
  return window['go']['app']['App']['OpenDocument'](arg1);
}

export function OpenDuotrope(arg1) {
  return window['go']['app']['App']['OpenDuotrope'](arg1);
}

export function OpenExportFolder() {
  return window['go']['app']['App']['OpenExportFolder']();
}

export function OpenKDPManuscriptSpecs() {
  return window['go']['app']['App']['OpenKDPManuscriptSpecs']();
}

export function OpenOrgOtherURL(arg1) {
  return window['go']['app']['App']['OpenOrgOtherURL'](arg1);
}

export function OpenOrgURL(arg1) {
  return window['go']['app']['App']['OpenOrgURL'](arg1);
}

export function OpenStatusBar() {
  return window['go']['app']['App']['OpenStatusBar']();
}

export function OpenSupportingItem(arg1) {
  return window['go']['app']['App']['OpenSupportingItem'](arg1);
}

export function OpenTemplate(arg1) {
  return window['go']['app']['App']['OpenTemplate'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['app']['App']['OpenURL'](arg1);
}

export function PathExists(arg1) {
  return window['go']['app']['App']['PathExists'](arg1);
}

export function PreviewImportFiles() {
  return window['go']['app']['App']['PreviewImportFiles']();
}

export function PrintWork(arg1) {
  return window['go']['app']['App']['PrintWork'](arg1);
}

export function RefreshReport(arg1) {
  return window['go']['app']['App']['RefreshReport'](arg1);
}

export function RegeneratePDF(arg1) {
  return window['go']['app']['App']['RegeneratePDF'](arg1);
}

export function RemoveWorkFromCollection(arg1, arg2) {
  return window['go']['app']['App']['RemoveWorkFromCollection'](arg1, arg2);
}

export function RenameFieldValue(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameFieldValue'](arg1, arg2, arg3, arg4);
}

export function ReorderCollectionWorks(arg1, arg2) {
  return window['go']['app']['App']['ReorderCollectionWorks'](arg1, arg2);
}

export function ReportFileSystemChecks() {
  return window['go']['app']['App']['ReportFileSystemChecks']();
}

export function RestoreBackup(arg1) {
  return window['go']['app']['App']['RestoreBackup'](arg1);
}

export function RestoreBackupAndQuit(arg1) {
  return window['go']['app']['App']['RestoreBackupAndQuit'](arg1);
}

export function SaveCoverFromBytes(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveCoverFromBytes'](arg1, arg2, arg3, arg4);
}

export function SaveWindowGeometry(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveWindowGeometry'](arg1, arg2, arg3, arg4);
}

export function ScanImportFolder() {
  return window['go']['app']['App']['ScanImportFolder']();
}

export function Search(arg1, arg2) {
  return window['go']['app']['App']['Search'](arg1, arg2);
}

export function SelectBookTemplate() {
  return window['go']['app']['App']['SelectBookTemplate']();
}

export function SelectCoverImage(arg1) {
  return window['go']['app']['App']['SelectCoverImage'](arg1);
}

export function SelectExportFolder() {
  return window['go']['app']['App']['SelectExportFolder']();
}

export function SetCollectionIsBook(arg1, arg2) {
  return window['go']['app']['App']['SetCollectionIsBook'](arg1, arg2);
}

export function SetDashboardTimeframe(arg1) {
  return window['go']['app']['App']['SetDashboardTimeframe'](arg1);
}

export function SetLastCollectionID(arg1) {
  return window['go']['app']['App']['SetLastCollectionID'](arg1);
}

export function SetLastCollectionType(arg1) {
  return window['go']['app']['App']['SetLastCollectionType'](arg1);
}

export function SetLastOrgID(arg1) {
  return window['go']['app']['App']['SetLastOrgID'](arg1);
}

export function SetLastRoute(arg1) {
  return window['go']['app']['App']['SetLastRoute'](arg1);
}

export function SetLastSubmissionID(arg1) {
  return window['go']['app']['App']['SetLastSubmissionID'](arg1);
}

export function SetLastWorkID(arg1) {
  return window['go']['app']['App']['SetLastWorkID'](arg1);
}

export function SetShowDeleted(arg1) {
  return window['go']['app']['App']['SetShowDeleted'](arg1);
}

export function SetSidebarWidth(arg1) {
  return window['go']['app']['App']['SetSidebarWidth'](arg1);
}

export function SetTab(arg1, arg2) {
  return window['go']['app']['App']['SetTab'](arg1, arg2);
}

export function SetTableState(arg1, arg2) {
  return window['go']['app']['App']['SetTableState'](arg1, arg2);
}

export function SetWorkMarked(arg1, arg2) {
  return window['go']['app']['App']['SetWorkMarked'](arg1, arg2);
}

export function SetWorkSkipAudits(arg1, arg2) {
  return window['go']['app']['App']['SetWorkSkipAudits'](arg1, arg2);
}

export function SetWorkSuppressed(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetWorkSuppressed'](arg1, arg2, arg3);
}

export function SetWorksMarked(arg1, arg2) {
  return window['go']['app']['App']['SetWorksMarked'](arg1, arg2);
}

export function StartReportGeneration() {
  return window['go']['app']['App']['StartReportGeneration']();
}

export function SyncWorkTemplate(arg1) {
  return window['go']['app']['App']['SyncWorkTemplate'](arg1);
}

export function TestProviderConnection(arg1, arg2) {
  return window['go']['app']['App']['TestProviderConnection'](arg1, arg2);
}

export function ToggleCollectionMarks(arg1) {
  return window['go']['app']['App']['ToggleCollectionMarks'](arg1);
}

export function ToggleCollectionSuppressed(arg1) {
  return window['go']['app']['App']['ToggleCollectionSuppressed'](arg1);
}

export function ToggleShowDeleted() {
  return window['go']['app']['App']['ToggleShowDeleted']();
}

export function TouchWorkAccessDate(arg1) {
  return window['go']['app']['App']['TouchWorkAccessDate'](arg1);
}

export function UndeleteCollection(arg1) {
  return window['go']['app']['App']['UndeleteCollection'](arg1);
}

export function UndeleteNote(arg1) {
  return window['go']['app']['App']['UndeleteNote'](arg1);
}

export function UndeleteOrganization(arg1) {
  return window['go']['app']['App']['UndeleteOrganization'](arg1);
}

export function UndeleteSubmission(arg1) {
  return window['go']['app']['App']['UndeleteSubmission'](arg1);
}

export function UndeleteWork(arg1) {
  return window['go']['app']['App']['UndeleteWork'](arg1);
}

export function UndismissAnnotation(arg1) {
  return window['go']['app']['App']['UndismissAnnotation'](arg1);
}

export function UpdateBook(arg1) {
  return window['go']['app']['App']['UpdateBook'](arg1);
}

export function UpdateCollection(arg1) {
  return window['go']['app']['App']['UpdateCollection'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['app']['App']['UpdateNote'](arg1);
}

export function UpdateOrganization(arg1) {
  return window['go']['app']['App']['UpdateOrganization'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UpdateSubmission(arg1) {
  return window['go']['app']['App']['UpdateSubmission'](arg1);
}

export function UpdateWork(arg1) {
  return window['go']['app']['App']['UpdateWork'](arg1);
}

export function UpdateWorkWithWorkflow(arg1) {
  return window['go']['app']['App']['UpdateWorkWithWorkflow'](arg1);
}

export function ValidateContent(arg1) {
  return window['go']['app']['App']['ValidateContent'](arg1);
}

export function ValidateCover(arg1) {
  return window['go']['app']['App']['ValidateCover'](arg1);
}

export function ValidateCoverImagePath(arg1) {
  return window['go']['app']['App']['ValidateCoverImagePath'](arg1);
}

export function ValidateMatter(arg1) {
  return window['go']['app']['App']['ValidateMatter'](arg1);
}

export function ValidateTemplate(arg1) {
  return window['go']['app']['App']['ValidateTemplate'](arg1);
}
