// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {backup} from '../models';
import {models} from '../models';
import {validation} from '../models';
import {fts} from '../models';
import {state} from '../models';
import {db} from '../models';
import {fileops} from '../models';
import {settings} from '../models';

export function AddExtensionAndContinue(arg1:string):Promise<app.ImportResult>;

export function AddSearchHistory(arg1:string):Promise<void>;

export function AddTypeAndContinue(arg1:string):Promise<app.ImportResult>;

export function AddWorkToCollection(arg1:number,arg2:number):Promise<void>;

export function AnalyzeCollectionHeadings(arg1:number):Promise<app.CollectionHeadingAnalysisResult>;

export function AuditCollectionStyles(arg1:number):Promise<app.CollectionAuditSummary>;

export function AuditWorkStyles(arg1:number,arg2:string):Promise<app.StyleAuditResult>;

export function AutoImportFiles(arg1:number):Promise<app.ImportResult>;

export function AutoImportFilesWithEdits(arg1:number,arg2:Array<app.FileEdit>):Promise<app.ImportResult>;

export function BrowseForFolder(arg1:string):Promise<string>;

export function CancelImport():Promise<void>;

export function CheckImportConflict(arg1:string):Promise<app.ImportConflict>;

export function CheckLibreOffice():Promise<boolean>;

export function CheckWorkPath(arg1:number):Promise<app.PathCheckResult>;

export function ClearPartCache(arg1:number,arg2:Array<string>):Promise<void>;

export function CloseStatusBar():Promise<void>;

export function CompleteSetup():Promise<void>;

export function CopyCoverToClipboard(arg1:string):Promise<void>;

export function CopyTemplateToLibrary(arg1:string,arg2:string):Promise<string>;

export function CreateBackup(arg1:string):Promise<backup.BackupInfo>;

export function CreateBook(arg1:models.Book):Promise<void>;

export function CreateCollection(arg1:models.Collection):Promise<validation.ValidationResult>;

export function CreateNewWork(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Work>;

export function CreateNote(arg1:models.Note):Promise<validation.ValidationResult>;

export function CreateOrganization(arg1:models.Organization):Promise<validation.ValidationResult>;

export function CreateSubmission(arg1:models.Submission):Promise<validation.ValidationResult>;

export function CreateWork(arg1:models.Work):Promise<validation.ValidationResult>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteBook(arg1:number):Promise<void>;

export function DeleteCollection(arg1:number):Promise<void>;

export function DeleteCollectionPermanent(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteNotePermanent(arg1:number):Promise<void>;

export function DeleteOrganization(arg1:number):Promise<void>;

export function DeleteOrganizationPermanent(arg1:number):Promise<void>;

export function DeleteSubmission(arg1:number):Promise<void>;

export function DeleteSubmissionPermanent(arg1:number):Promise<void>;

export function DeleteWork(arg1:number):Promise<void>;

export function DeleteWorkPermanent(arg1:number,arg2:boolean):Promise<void>;

export function DetectLibreOffice():Promise<string>;

export function EmitStatus(arg1:string,arg2:string):Promise<void>;

export function EnsureTemplatesDir():Promise<void>;

export function ExportAllCSV():Promise<Array<app.ExportResult>>;

export function ExportAllTables():Promise<Array<app.ExportResult>>;

export function ExportBookPDF(arg1:number):Promise<app.BookExportResult>;

export function ExportBookPDFWithParts(arg1:number,arg2:Array<number>,arg3:boolean):Promise<app.BookExportResult>;

export function ExportCollectionFolder(arg1:number):Promise<number>;

export function ExportToSubmissions(arg1:number):Promise<string>;

export function FTSBatchContent(arg1:Array<number>):Promise<Array<fts.ExtractionResult>>;

export function FTSBuildIndex():Promise<fts.BuildReport>;

export function FTSCheckStaleness():Promise<fts.StalenessReport>;

export function FTSDeleteIndex():Promise<void>;

export function FTSGetContent(arg1:number):Promise<fts.ExtractionResult>;

export function FTSGetStatus():Promise<fts.Status>;

export function FTSSearch(arg1:fts.Query):Promise<fts.SearchResponse>;

export function FTSUpdateIndex():Promise<fts.BuildReport>;

export function GeneratePath(arg1:number):Promise<string>;

export function GetAllSubmissionViews():Promise<Array<models.SubmissionView>>;

export function GetAppState():Promise<state.AppState>;

export function GetBook(arg1:number):Promise<models.Book>;

export function GetBookByCollection(arg1:number):Promise<models.Book>;

export function GetBookParts(arg1:number):Promise<Array<app.PartInfo>>;

export function GetCollection(arg1:number):Promise<models.Collection>;

export function GetCollectionDeleteConfirmation(arg1:number):Promise<db.DeleteConfirmation>;

export function GetCollectionHasMarkedWorks(arg1:number):Promise<boolean>;

export function GetCollectionHasSuppressedWorks(arg1:number):Promise<boolean>;

export function GetCollectionIsBook(arg1:number):Promise<boolean>;

export function GetCollectionWorks(arg1:number):Promise<Array<models.CollectionWork>>;

export function GetCollections():Promise<Array<models.CollectionView>>;

export function GetCoverImageData(arg1:string):Promise<string>;

export function GetCoversDir():Promise<string>;

export function GetDashboardStats(arg1:string):Promise<app.DashboardStats>;

export function GetDefaultTemplatePath():Promise<string>;

export function GetDistinctValues(arg1:string,arg2:string):Promise<Array<string>>;

export function GetDuotropeURL(arg1:number):Promise<string>;

export function GetEnumLists():Promise<app.EnumLists>;

export function GetExportFolderPath():Promise<string>;

export function GetExportTables():Promise<Array<app.TableInfo>>;

export function GetFileConfig():Promise<fileops.Config>;

export function GetFileModTimes(arg1:number):Promise<app.FileModTimes>;

export function GetFileServerPort():Promise<number>;

export function GetNotes(arg1:string,arg2:number):Promise<Array<models.Note>>;

export function GetOrganization(arg1:number):Promise<models.Organization>;

export function GetOrganizationDeleteConfirmation(arg1:number):Promise<db.DeleteConfirmation>;

export function GetOrganizations():Promise<Array<models.Organization>>;

export function GetOrganizationsWithNotes():Promise<Array<models.OrganizationWithNotes>>;

export function GetOrgsFilterOptions():Promise<app.OrgsFilterOptions>;

export function GetPartCacheStatus(arg1:number):Promise<Record<number, boolean>>;

export function GetPreviewURL(arg1:number):Promise<string>;

export function GetReportNames():Promise<Array<string>>;

export function GetSavedPartSelection(arg1:number):Promise<Array<number>>;

export function GetSearchHistory():Promise<Array<string>>;

export function GetSettings():Promise<settings.Settings>;

export function GetSubmission(arg1:number):Promise<models.Submission>;

export function GetSubmissionDeleteConfirmation(arg1:number):Promise<db.DeleteConfirmation>;

export function GetSubmissionViewsByCollection(arg1:number):Promise<Array<models.SubmissionView>>;

export function GetSubmissionViewsByOrg(arg1:number):Promise<Array<models.SubmissionView>>;

export function GetSubmissionViewsByWork(arg1:number):Promise<Array<models.SubmissionView>>;

export function GetSubmissions():Promise<Array<models.Submission>>;

export function GetSubmissionsByWork(arg1:number):Promise<Array<models.Submission>>;

export function GetSubmissionsFilterOptions():Promise<app.SubmissionsFilterOptions>;

export function GetSupportingInfo(arg1:number):Promise<fileops.SupportingInfo>;

export function GetTab(arg1:string):Promise<string>;

export function GetTableState(arg1:string):Promise<state.TableState>;

export function GetTemplatesDir():Promise<string>;

export function GetValidExtensions():Promise<Array<string>>;

export function GetWork(arg1:number):Promise<models.Work>;

export function GetWorkBookAuditStatus(arg1:number):Promise<app.WorkBookAuditStatus>;

export function GetWorkCollections(arg1:number):Promise<Array<models.CollectionDetail>>;

export function GetWorkDeleteConfirmation(arg1:number):Promise<db.DeleteConfirmation>;

export function GetWorkFullPath(arg1:number):Promise<string>;

export function GetWorkMarked(arg1:number):Promise<boolean>;

export function GetWorkTemplatePath(arg1:number):Promise<string>;

export function GetWorks():Promise<Array<models.WorkView>>;

export function GetWorksFilterOptions():Promise<app.WorksFilterOptions>;

export function HasCollectionParts(arg1:number):Promise<boolean>;

export function ImportWork(arg1:string,arg2:fileops.ParsedFilename):Promise<models.Work>;

export function IsFirstRun():Promise<boolean>;

export function IsValidExtension(arg1:string):Promise<boolean>;

export function ListBackups():Promise<Array<backup.BackupInfo>>;

export function ListTemplates():Promise<Array<string>>;

export function MoveWorkFile(arg1:number):Promise<void>;

export function OpenBookPDF(arg1:number):Promise<app.OpenBookPDFResult>;

export function OpenDocument(arg1:number):Promise<void>;

export function OpenDuotrope(arg1:number):Promise<void>;

export function OpenExportFolder():Promise<void>;

export function OpenOrgOtherURL(arg1:number):Promise<void>;

export function OpenOrgURL(arg1:number):Promise<void>;

export function OpenStatusBar():Promise<void>;

export function OpenSupportingItem(arg1:number):Promise<void>;

export function OpenTemplate(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PathExists(arg1:string):Promise<boolean>;

export function PreviewImportFiles():Promise<app.ImportPreview>;

export function PrintWork(arg1:number):Promise<void>;

export function RefreshReport(arg1:string):Promise<void>;

export function RegeneratePDF(arg1:number):Promise<string>;

export function ReimportFromCSV():Promise<void>;

export function RemoveWorkFromCollection(arg1:number,arg2:number):Promise<void>;

export function RenameFieldValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<number>;

export function ReorderCollectionWorks(arg1:number,arg2:Array<number>):Promise<void>;

export function ReportFileSystemChecks():Promise<app.ReportCategory>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SaveCoverFromBytes(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SaveWindowGeometry(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function ScanImportFolder():Promise<Array<string>>;

export function Search(arg1:string,arg2:number):Promise<models.SearchResponse>;

export function SelectBookTemplate():Promise<string>;

export function SelectCoverImage(arg1:string):Promise<string>;

export function SelectExportFolder():Promise<string>;

export function SetCollectionIsBook(arg1:number,arg2:boolean):Promise<void>;

export function SetDashboardTimeframe(arg1:string):Promise<void>;

export function SetLastCollectionID(arg1:number):Promise<void>;

export function SetLastCollectionType(arg1:string):Promise<void>;

export function SetLastOrgID(arg1:number):Promise<void>;

export function SetLastRoute(arg1:string):Promise<void>;

export function SetLastSubmissionID(arg1:number):Promise<void>;

export function SetLastWorkID(arg1:number):Promise<void>;

export function SetShowDeleted(arg1:boolean):Promise<void>;

export function SetSidebarWidth(arg1:number):Promise<void>;

export function SetTab(arg1:string,arg2:string):Promise<void>;

export function SetTableState(arg1:string,arg2:state.TableState):Promise<void>;

export function SetWorkMarked(arg1:number,arg2:boolean):Promise<void>;

export function SetWorkSuppressed(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function StartReportGeneration():Promise<void>;

export function SyncWorkTemplate(arg1:number):Promise<void>;

export function ToggleCollectionMarks(arg1:number):Promise<boolean>;

export function ToggleCollectionSuppressed(arg1:number):Promise<boolean>;

export function ToggleShowDeleted():Promise<boolean>;

export function TouchWorkAccessDate(arg1:number):Promise<void>;

export function UndeleteCollection(arg1:number):Promise<validation.ValidationResult>;

export function UndeleteNote(arg1:number):Promise<void>;

export function UndeleteOrganization(arg1:number):Promise<validation.ValidationResult>;

export function UndeleteSubmission(arg1:number):Promise<validation.ValidationResult>;

export function UndeleteWork(arg1:number):Promise<validation.ValidationResult>;

export function UpdateBook(arg1:models.Book):Promise<void>;

export function UpdateCollection(arg1:models.Collection):Promise<validation.ValidationResult>;

export function UpdateNote(arg1:models.Note):Promise<validation.ValidationResult>;

export function UpdateOrganization(arg1:models.Organization):Promise<validation.ValidationResult>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;

export function UpdateSubmission(arg1:models.Submission):Promise<validation.ValidationResult>;

export function UpdateWork(arg1:models.Work):Promise<validation.ValidationResult>;

export function UpdateWorkWithWorkflow(arg1:models.Work):Promise<app.WorkUpdateResult>;

export function ValidateTemplate(arg1:string):Promise<app.TemplateValidation>;
