// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWorkToCollection(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddWorkToCollection'](arg1, arg2, arg3);
}

export function BrowseForFolder(arg1) {
  return window['go']['main']['App']['BrowseForFolder'](arg1);
}

export function CheckLibreOffice() {
  return window['go']['main']['App']['CheckLibreOffice']();
}

export function CheckWorkPath(arg1) {
  return window['go']['main']['App']['CheckWorkPath'](arg1);
}

export function CompleteSetup() {
  return window['go']['main']['App']['CompleteSetup']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function CreateNewWork(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateNewWork'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNote(arg1) {
  return window['go']['main']['App']['CreateNote'](arg1);
}

export function CreateOrganization(arg1) {
  return window['go']['main']['App']['CreateOrganization'](arg1);
}

export function CreateSubmission(arg1) {
  return window['go']['main']['App']['CreateSubmission'](arg1);
}

export function CreateWork(arg1) {
  return window['go']['main']['App']['CreateWork'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['main']['App']['DeleteBackup'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteOrganization(arg1) {
  return window['go']['main']['App']['DeleteOrganization'](arg1);
}

export function DeleteSubmission(arg1) {
  return window['go']['main']['App']['DeleteSubmission'](arg1);
}

export function DeleteWork(arg1) {
  return window['go']['main']['App']['DeleteWork'](arg1);
}

export function DetectLibreOffice() {
  return window['go']['main']['App']['DetectLibreOffice']();
}

export function ExportAllCSV() {
  return window['go']['main']['App']['ExportAllCSV']();
}

export function ExportAllTables() {
  return window['go']['main']['App']['ExportAllTables']();
}

export function ExportToSubmissions(arg1) {
  return window['go']['main']['App']['ExportToSubmissions'](arg1);
}

export function GeneratePath(arg1) {
  return window['go']['main']['App']['GeneratePath'](arg1);
}

export function GetAllSubmissionViews() {
  return window['go']['main']['App']['GetAllSubmissionViews']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetCollectionWorks(arg1) {
  return window['go']['main']['App']['GetCollectionWorks'](arg1);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function GetDuotropeURL(arg1) {
  return window['go']['main']['App']['GetDuotropeURL'](arg1);
}

export function GetEnumLists() {
  return window['go']['main']['App']['GetEnumLists']();
}

export function GetExportFolderPath() {
  return window['go']['main']['App']['GetExportFolderPath']();
}

export function GetExportTables() {
  return window['go']['main']['App']['GetExportTables']();
}

export function GetFileConfig() {
  return window['go']['main']['App']['GetFileConfig']();
}

export function GetFileServerPort() {
  return window['go']['main']['App']['GetFileServerPort']();
}

export function GetNotes(arg1, arg2) {
  return window['go']['main']['App']['GetNotes'](arg1, arg2);
}

export function GetOrganization(arg1) {
  return window['go']['main']['App']['GetOrganization'](arg1);
}

export function GetOrganizations() {
  return window['go']['main']['App']['GetOrganizations']();
}

export function GetOrganizationsWithNotes() {
  return window['go']['main']['App']['GetOrganizationsWithNotes']();
}

export function GetOrgsFilterOptions() {
  return window['go']['main']['App']['GetOrgsFilterOptions']();
}

export function GetPreviewURL(arg1) {
  return window['go']['main']['App']['GetPreviewURL'](arg1);
}

export function GetReports() {
  return window['go']['main']['App']['GetReports']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubmission(arg1) {
  return window['go']['main']['App']['GetSubmission'](arg1);
}

export function GetSubmissionViewsByOrg(arg1) {
  return window['go']['main']['App']['GetSubmissionViewsByOrg'](arg1);
}

export function GetSubmissionViewsByWork(arg1) {
  return window['go']['main']['App']['GetSubmissionViewsByWork'](arg1);
}

export function GetSubmissions() {
  return window['go']['main']['App']['GetSubmissions']();
}

export function GetSubmissionsByWork(arg1) {
  return window['go']['main']['App']['GetSubmissionsByWork'](arg1);
}

export function GetSubmissionsFilterOptions() {
  return window['go']['main']['App']['GetSubmissionsFilterOptions']();
}

export function GetWork(arg1) {
  return window['go']['main']['App']['GetWork'](arg1);
}

export function GetWorkCollections(arg1) {
  return window['go']['main']['App']['GetWorkCollections'](arg1);
}

export function GetWorkFullPath(arg1) {
  return window['go']['main']['App']['GetWorkFullPath'](arg1);
}

export function GetWorks() {
  return window['go']['main']['App']['GetWorks']();
}

export function GetWorksFilterOptions() {
  return window['go']['main']['App']['GetWorksFilterOptions']();
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function ListBackups() {
  return window['go']['main']['App']['ListBackups']();
}

export function MoveWorkFile(arg1) {
  return window['go']['main']['App']['MoveWorkFile'](arg1);
}

export function OpenDocument(arg1) {
  return window['go']['main']['App']['OpenDocument'](arg1);
}

export function OpenDuotrope(arg1) {
  return window['go']['main']['App']['OpenDuotrope'](arg1);
}

export function OpenExportFolder() {
  return window['go']['main']['App']['OpenExportFolder']();
}

export function OpenOrgOtherURL(arg1) {
  return window['go']['main']['App']['OpenOrgOtherURL'](arg1);
}

export function OpenOrgURL(arg1) {
  return window['go']['main']['App']['OpenOrgURL'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function PrintWork(arg1) {
  return window['go']['main']['App']['PrintWork'](arg1);
}

export function RegeneratePDF(arg1) {
  return window['go']['main']['App']['RegeneratePDF'](arg1);
}

export function ReimportFromCSV() {
  return window['go']['main']['App']['ReimportFromCSV']();
}

export function RemoveWorkFromCollection(arg1, arg2) {
  return window['go']['main']['App']['RemoveWorkFromCollection'](arg1, arg2);
}

export function ReportFileSystemChecks() {
  return window['go']['main']['App']['ReportFileSystemChecks']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SaveWindowGeometry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWindowGeometry'](arg1, arg2, arg3, arg4);
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}

export function SearchNotesByText(arg1) {
  return window['go']['main']['App']['SearchNotesByText'](arg1);
}

export function SelectExportFolder() {
  return window['go']['main']['App']['SelectExportFolder']();
}

export function SetCollectionsFilter(arg1) {
  return window['go']['main']['App']['SetCollectionsFilter'](arg1);
}

export function SetLastCollectionID(arg1) {
  return window['go']['main']['App']['SetLastCollectionID'](arg1);
}

export function SetLastOrgID(arg1) {
  return window['go']['main']['App']['SetLastOrgID'](arg1);
}

export function SetLastRoute(arg1) {
  return window['go']['main']['App']['SetLastRoute'](arg1);
}

export function SetLastSubmissionID(arg1) {
  return window['go']['main']['App']['SetLastSubmissionID'](arg1);
}

export function SetLastWorkID(arg1) {
  return window['go']['main']['App']['SetLastWorkID'](arg1);
}

export function SetOrgsFilter(arg1) {
  return window['go']['main']['App']['SetOrgsFilter'](arg1);
}

export function SetOrgsPushcartsFilter(arg1, arg2) {
  return window['go']['main']['App']['SetOrgsPushcartsFilter'](arg1, arg2);
}

export function SetOrgsStatusFilter(arg1) {
  return window['go']['main']['App']['SetOrgsStatusFilter'](arg1);
}

export function SetOrgsSubmissionsFilter(arg1, arg2) {
  return window['go']['main']['App']['SetOrgsSubmissionsFilter'](arg1, arg2);
}

export function SetOrgsTimingFilter(arg1) {
  return window['go']['main']['App']['SetOrgsTimingFilter'](arg1);
}

export function SetOrgsTypeFilter(arg1) {
  return window['go']['main']['App']['SetOrgsTypeFilter'](arg1);
}

export function SetSubmissionsFilter(arg1) {
  return window['go']['main']['App']['SetSubmissionsFilter'](arg1);
}

export function SetSubmissionsResponseFilter(arg1) {
  return window['go']['main']['App']['SetSubmissionsResponseFilter'](arg1);
}

export function SetSubmissionsStatusFilter(arg1) {
  return window['go']['main']['App']['SetSubmissionsStatusFilter'](arg1);
}

export function SetSubmissionsTypeFilter(arg1) {
  return window['go']['main']['App']['SetSubmissionsTypeFilter'](arg1);
}

export function SetViewSort(arg1, arg2) {
  return window['go']['main']['App']['SetViewSort'](arg1, arg2);
}

export function SetWorksFilter(arg1) {
  return window['go']['main']['App']['SetWorksFilter'](arg1);
}

export function SetWorksQualityFilter(arg1) {
  return window['go']['main']['App']['SetWorksQualityFilter'](arg1);
}

export function SetWorksStatusFilter(arg1) {
  return window['go']['main']['App']['SetWorksStatusFilter'](arg1);
}

export function SetWorksTypeFilter(arg1) {
  return window['go']['main']['App']['SetWorksTypeFilter'](arg1);
}

export function SetWorksYearFilter(arg1) {
  return window['go']['main']['App']['SetWorksYearFilter'](arg1);
}

export function TouchWorkAccessDate(arg1) {
  return window['go']['main']['App']['TouchWorkAccessDate'](arg1);
}

export function UpdateCollection(arg1) {
  return window['go']['main']['App']['UpdateCollection'](arg1);
}

export function UpdateNote(arg1) {
  return window['go']['main']['App']['UpdateNote'](arg1);
}

export function UpdateOrganization(arg1) {
  return window['go']['main']['App']['UpdateOrganization'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSubmission(arg1) {
  return window['go']['main']['App']['UpdateSubmission'](arg1);
}

export function UpdateWork(arg1) {
  return window['go']['main']['App']['UpdateWork'](arg1);
}

export function UpdateWorkPathToGenerated(arg1) {
  return window['go']['main']['App']['UpdateWorkPathToGenerated'](arg1);
}

export function UpdateWorkWithWorkflow(arg1) {
  return window['go']['main']['App']['UpdateWorkWithWorkflow'](arg1);
}
