// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {backup} from '../models';
import {models} from '../models';
import {state} from '../models';
import {fileops} from '../models';
import {settings} from '../models';

export function AddSearchHistory(arg1:string):Promise<void>;

export function AddWorkToCollection(arg1:number,arg2:number):Promise<void>;

export function BrowseForFolder(arg1:string):Promise<string>;

export function CheckLibreOffice():Promise<boolean>;

export function CheckWorkPath(arg1:number):Promise<main.PathCheckResult>;

export function CompleteSetup():Promise<void>;

export function CreateBackup(arg1:string):Promise<backup.BackupInfo>;

export function CreateCollection(arg1:models.Collection):Promise<void>;

export function CreateNewWork(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<models.Work>;

export function CreateNote(arg1:models.Note):Promise<void>;

export function CreateOrganization(arg1:models.Organization):Promise<void>;

export function CreateSubmission(arg1:models.Submission):Promise<void>;

export function CreateWork(arg1:models.Work):Promise<void>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function DeleteOrganization(arg1:number):Promise<void>;

export function DeleteSubmission(arg1:number):Promise<void>;

export function DeleteWork(arg1:number):Promise<void>;

export function DetectLibreOffice():Promise<string>;

export function ExportAllCSV():Promise<Array<main.ExportResult>>;

export function ExportAllTables():Promise<Array<main.ExportResult>>;

export function ExportToSubmissions(arg1:number):Promise<string>;

export function GeneratePath(arg1:number):Promise<string>;

export function GetAllSubmissionViews():Promise<Array<models.SubmissionView>>;

export function GetAppState():Promise<state.AppState>;

export function GetCollection(arg1:number):Promise<models.Collection>;

export function GetCollectionWorks(arg1:number):Promise<Array<models.Work>>;

export function GetCollections():Promise<Array<models.Collection>>;

export function GetDuotropeURL(arg1:number):Promise<string>;

export function GetEnumLists():Promise<main.EnumLists>;

export function GetExportFolderPath():Promise<string>;

export function GetExportTables():Promise<Array<main.TableInfo>>;

export function GetFileConfig():Promise<fileops.Config>;

export function GetFileServerPort():Promise<number>;

export function GetNotes(arg1:string,arg2:number):Promise<Array<models.Note>>;

export function GetOrganization(arg1:number):Promise<models.Organization>;

export function GetOrganizations():Promise<Array<models.Organization>>;

export function GetOrganizationsWithNotes():Promise<Array<models.OrganizationWithNotes>>;

export function GetOrgsFilterOptions():Promise<main.OrgsFilterOptions>;

export function GetPreviewURL(arg1:number):Promise<string>;

export function GetRecentlyChanged(arg1:number):Promise<Array<models.RecentChange>>;

export function GetReports():Promise<main.ReportsResult>;

export function GetSearchHistory():Promise<Array<string>>;

export function GetSettings():Promise<settings.Settings>;

export function GetSubmission(arg1:number):Promise<models.Submission>;

export function GetSubmissionViewsByOrg(arg1:number):Promise<Array<models.SubmissionView>>;

export function GetSubmissionViewsByWork(arg1:number):Promise<Array<models.SubmissionView>>;

export function GetSubmissions():Promise<Array<models.Submission>>;

export function GetSubmissionsByWork(arg1:number):Promise<Array<models.Submission>>;

export function GetSubmissionsFilterOptions():Promise<main.SubmissionsFilterOptions>;

export function GetWork(arg1:number):Promise<models.Work>;

export function GetWorkCollections(arg1:number):Promise<Array<models.CollectionDetail>>;

export function GetWorkFullPath(arg1:number):Promise<string>;

export function GetWorks():Promise<Array<models.Work>>;

export function GetWorksFilterOptions():Promise<main.WorksFilterOptions>;

export function IsFirstRun():Promise<boolean>;

export function ListBackups():Promise<Array<backup.BackupInfo>>;

export function MoveWorkFile(arg1:number):Promise<void>;

export function OpenDocument(arg1:number):Promise<void>;

export function OpenDuotrope(arg1:number):Promise<void>;

export function OpenExportFolder():Promise<void>;

export function OpenOrgOtherURL(arg1:number):Promise<void>;

export function OpenOrgURL(arg1:number):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function PathExists(arg1:string):Promise<boolean>;

export function PrintWork(arg1:number):Promise<void>;

export function RegeneratePDF(arg1:number):Promise<string>;

export function ReimportFromCSV():Promise<void>;

export function RemoveWorkFromCollection(arg1:number,arg2:number):Promise<void>;

export function ReorderCollectionWorks(arg1:number,arg2:Array<number>):Promise<void>;

export function ReportFileSystemChecks():Promise<main.ReportCategory>;

export function RestoreBackup(arg1:string):Promise<void>;

export function SaveWindowGeometry(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function Search(arg1:string,arg2:number):Promise<Array<models.SearchResult>>;

export function SelectExportFolder():Promise<string>;

export function SetCollectionsFilter(arg1:string):Promise<void>;

export function SetLastCollectionID(arg1:number):Promise<void>;

export function SetLastOrgID(arg1:number):Promise<void>;

export function SetLastRoute(arg1:string):Promise<void>;

export function SetLastSubmissionID(arg1:number):Promise<void>;

export function SetLastWorkID(arg1:number):Promise<void>;

export function SetOrgsFilter(arg1:string):Promise<void>;

export function SetOrgsPushcartsFilter(arg1:any,arg2:any):Promise<void>;

export function SetOrgsStatusFilter(arg1:Array<string>):Promise<void>;

export function SetOrgsSubmissionsFilter(arg1:any,arg2:any):Promise<void>;

export function SetOrgsTimingFilter(arg1:Array<string>):Promise<void>;

export function SetOrgsTypeFilter(arg1:Array<string>):Promise<void>;

export function SetSubmissionsFilter(arg1:string):Promise<void>;

export function SetSubmissionsResponseFilter(arg1:Array<string>):Promise<void>;

export function SetSubmissionsStatusFilter(arg1:Array<string>):Promise<void>;

export function SetSubmissionsTypeFilter(arg1:Array<string>):Promise<void>;

export function SetViewSort(arg1:string,arg2:state.ViewSort):Promise<void>;

export function SetWorksFilter(arg1:string):Promise<void>;

export function SetWorksQualityFilter(arg1:Array<string>):Promise<void>;

export function SetWorksStatusFilter(arg1:Array<string>):Promise<void>;

export function SetWorksTypeFilter(arg1:Array<string>):Promise<void>;

export function SetWorksYearFilter(arg1:Array<string>):Promise<void>;

export function TouchWorkAccessDate(arg1:number):Promise<void>;

export function UpdateCollection(arg1:models.Collection):Promise<void>;

export function UpdateNote(arg1:models.Note):Promise<void>;

export function UpdateOrganization(arg1:models.Organization):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;

export function UpdateSubmission(arg1:models.Submission):Promise<void>;

export function UpdateWork(arg1:models.Work):Promise<void>;

export function UpdateWorkPathToGenerated(arg1:number):Promise<void>;

export function UpdateWorkWithWorkflow(arg1:models.Work):Promise<main.WorkUpdateResult>;
